services:

  fastapi:
    build: ./app
    container_name: fastapi
    ports:
      - "80:80"
    environment:
      DATABASE_USERS_URL: postgresql://user:password@10.1.90.121:5432/users_db
      DATABASE_DATA_URL: postgresql://user:password@10.1.90.122:5432/frontend_data_db
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: docker_frontend

    ports:
      - "8080:80"

    depends_on:
      - fastapi

    networks:
      - app_network

    restart: unless-stopped

  enforcer:
    pid: host
    image: neuvector/enforcer:5.5.3
    container_name: enforcer
    privileged: true
    network_mode: host
    environment:
      # Controller-IP bleibt immer gleich
      - CLUSTER_JOIN_ADDR=10.1.90.120
      # Eigene IP der neuen VM
      - CLUSTER_ADVERTISE_ADDR=10.1.90.123 
    volumes:
      - /home/follertb/certs/internal:/etc/neuvector/certs/internal:ro
      - /lib/modules:/lib/modules
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys/fs/cgroup/:/host/cgroup/:ro
    restart: always
networks:
  app_network:
    driver: bridge
