services:
  fastapi:
    build: ./app
    container_name: docker_b_fastapi
    ports:
      - "80:80"
    environment:
      DATABASE_USERS_URL: postgresql://user:password@10.1.90.121:5432/users_db
      DATABASE_DATA_URL: postgresql://user:password@10.1.90.122:5432/frontend_data_db
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: docker_b_frontend

    ports:
      - "8080:80"

    depends_on:
      - fastapi

    networks:
      - app_network

    restart: unless-stopped


  allinone:
    pid: host
    image: neuvector/allinone:5.5.3
    container_name: allinone
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=10.1.90.120
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 8443:8443
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro

volumes:
  neuvector-certs:
  neuvector-data:

networks:
  app_network:
    driver: bridge